"""Verify schema sync

Revision ID: 00812371c96e
Revises: 
Create Date: 2025-04-11 19:59:00.999971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00812371c96e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
