"""Add notes to EmployeeHistory

Revision ID: 03eee33d9efb
Revises: 80c1e47b240f
Create Date: 2025-04-11 20:11:29.924433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03eee33d9efb'
down_revision = '80c1e47b240f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_history', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
