"""Add EmployeeHistory model

Revision ID: 80c1e47b240f
Revises: f4a1519100dc
Create Date: 2025-04-11 20:07:50.817445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c1e47b240f'
down_revision = 'f4a1519100dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_history_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_history_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_history_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_history_project_id'))
        batch_op.drop_index(batch_op.f('ix_employee_history_level_id'))
        batch_op.drop_index(batch_op.f('ix_employee_history_employee_id'))

    op.drop_table('employee_history')
    # ### end Alembic commands ###
