"""Add linkedin_url to Employee model

Revision ID: f4a1519100dc
Revises: b20727dbdc4c
Create Date: 2025-04-11 20:04:27.188291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a1519100dc'
down_revision = 'b20727dbdc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('linkedin_url')

    # ### end Alembic commands ###
